name: Test Suite
on: push
jobs:
  test:
    runs-on: buildjet-4vcpu-ubuntu-2204
    name: Test
    steps:
      - uses: actions/checkout@v2
      - run: curl https://checkip.amazonaws.com/
      - run: cat /proc/cpuinfo
